version: "3"

services:
  postgres:
    image: postgres
    container_name: epub_postgres
    environment:
      - POSTGRES_DB=epub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
     - '5432:5432'

  server:
    container_name: server
    depends_on:
      - postgres
    build: ./
    ports:
      - 8080:8080